name: Gamemode-Perms-by-supercrafter333
api:
- 3.10.0
- 3.11.0
- 3.12.0
- 3.13.0
- 3.14.0
mcpe-version:
- 388
- 389
- 390
- 407
version: 1.3.0-by-supercrafter333
main: gmperms\supercrafter333\main
author: supercrafter333
load: STARTUP
commands:
  gamo0:
    description: ยง1Gehe in den Survival Spielmodus!
    usage: "/gamo0"
    permission: gamo.0
     aliases: ["gm0"]
  gamo1:
    description: ยง1Gehe in den Kreativ Spielmodus!
    usage: "/gamo1"
    permission: gamo.1
     aliases: ["gm1"]
  gamo2:
    description: ยง1Gehe in den Abenteuer Spielmodus!
    usage: "/gamo2"
    permission: gamo.2
     aliases: ["gm32"]
  gamo3:
    description: ยง1Gehe in den Zuschauer Spielmodus!
    usage: "/gamo3"
    permission: gamo.3
    aliases: ["gm3"]
